website/views/account.py
from flask import g, request, url_for, redirect, session, render_template, make_response, current_app, Blueprint, abort, jsonify

from website import models, forms
from website.extensions import db
import uuid
import sys
from datetime import datetime
from ipaddress import ip_address

app = current_app
bp = Blueprint('account', __name__, url_prefix='/account')


@bp.route('/')
def home():
    if not isLoggedIn():
        return redirect(url_for('account.login'))

    userinfo = models.User.by_username(g.user.username)
    storyLen = models.Story.count_by_username(g.user.username)
    return render_template('pages/account.html', user=userinfo, storylen=storyLen)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if g.user:
        return redirect(redirect_url())

    form = forms.LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data.strip()
        password = form.password.data

        user = models.User.by_username(username)
        if (not user or password.join(user.salt) != (user.password)):
            return redirect(url_for('account.login', error='valfail'))

        user.last_login_date = datetime.utcnow()
        user.last_login_ip = ip_address(request.remote_addr).packed

        db.session.add(user)
        db.session.commit()

        g.user = user
        session['user_id'] = user.id
        session.permanent = True
        session.modified = True
        return redirect(redirect_url())

    return render_template('pages/login.html', form=form, error=request.args.get('error'))


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if g.user:
        return redirect(url_for(redirect_url()))

    form = forms.SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = models.generateSalt()
        user = models.User(username=form.username.data.strip(),
                           password=form.password.data,
                           salt=salt,
                           last_ip = ip_address(request.remote_addr).packed)
        db.session.add(user)
        db.session.commit()

        g.user = user
        session['user_id'] = user.id
        session.permanent = True
        session.modified = True
        return redirect(url_for('main.home'))

    return render_template('pages/signup.html', form=form)


@bp.route('/logout')
def logout():
    g.user = None
    session.permanent = False
    session.modified = False
    
    response = make_response(redirect(url_for('main.home')))
    response.set_cookie(app.session_cookie_name, expires=0)
    return response


@bp.route('/delete')
@bp.route('/delete/<username>')
@bp.route('/delete/<username>/<token>', methods=['POST'])
def delete(username = None, token = None):
    if g.user == None or username != g.user.username:
        abort(404)
        return
    # Update this to its own table in db
    if token is None:
        tempTok = uuid.uuid4().hex
        session['delete_token'] = tempTok
        return jsonify(tempTok)

    if token is not None and 'delete_token' not in session:
        abort(403)
        return

    if token is not None and 'delete_token' in session and g.user.username == username:
        if token != session['delete_token']:
            abort(403)
            return
        
        user = models.User.by_username(g.user.username)
        models.Story.delete_by_username(g.user.username)
        db.session.delete(user)
        db.session.commit()

        return redirect(url_for('account.logout'))

    return redirect(redirect_url())



@bp.route('/settings')
def settings():
    userinfo = models.User.by_username(g.user.username)
    storyLen = models.Story.count_by_username(g.user.username)
    last_ip += "{0}".format(ip_address(userinfo.last_login_ip))

    return render_template('pages/account.html', user=userinfo, storylen=storyLen, last_ip = ip)


@bp.route('/stories')
def stories():
    userinfo = models.User.by_username(g.user.username)
    stories = models.Story.list_by_username(g.user.username)
    storyLen = models.Story.count_by_username(g.user.username)

    return render_template('pages/account.html', user=userinfo, stories=stories, storylen=storyLen)



def redirect_url():
    home_url = url_for('main.home')

    url = request.args.get('next') or \
        request.referrer or \
        home_url
    if url == request.url:
        return home_url

    return url


def isLoggedIn():
    return g.user is not None

website/views/admin.py
from flask import g, request, url_for, redirect, session, render_template, make_response, current_app, Blueprint

from website import models, forms
from website.extensions import db

app = current_app
bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.route('/')
def home():
    return 'test'

website/views/main.py
import flask
from datetime import datetime, timedelta
from website import models, forms
from website.views.account import isLoggedIn, logout
from ipaddress import ip_address

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.app_errorhandler(404)
def page_not_found(e):
    return flask.render_template('errors/404.html'), 404


@bp.before_app_request
def before_request():
    flask.g.user = None
    if 'user_id' in flask.session:
        user = models.User.by_id(flask.session['user_id'])
        if not user:
            return logout()

        flask.g.user = user
        
        if 'timeout' not in flask.session or flask.session['timeout'] < datetime.now():
            flask.session['timeout'] = datetime.now() + timedelta(days=7)
            flask.session.permanent = True
            flask.session.modified = True
            models.User.update_last_login(user.id, {'last_login_date': datetime.utcnow(), 'last_login_ip': ip_address(flask.request.remote_addr).packed})


@bp.app_template_filter('timeformatted')
def _jinja_datetime(date, format='%d/%b/%Y'):
    return date.strftime(format)



def isMobile():
    ua = flask.request.user_agent
    return ua.platform == 'iphone' or ua.platform == 'android' or ua.platform == 'ipad'


@bp.route('/home')
@bp.route('/')
def home():
    return flask.render_template('pages/index.html', loggedin=isLoggedIn())

website/views/story.py
from flask import g, request, url_for, redirect, session, render_template, make_response, current_app, Blueprint, abort

from website import models, forms
from website.extensions import db
from website.views.main import isMobile
from website.views.account import isLoggedIn, redirect_url

import base64
import uuid

app = current_app
bp = Blueprint('story', __name__, url_prefix='/story')


@bp.route('/list', defaults={'extra': None})
@bp.route('/list/<extra>')
def list(extra=None):
    if not isMobile():
        stories = models.Story.get_list()
        if extra is not None:
            extra = extra.lower()
            if extra != 'top' and extra != 'latest' and extra != 'alphabetical':
                return abort(404)
        return render_template('pages/list.html', sort=extra, result=stories, loggedin=isLoggedIn())


@bp.route('/read/<url>')
def read(url):
    story = models.Story.by_url(url)

    if story:
        return render_template('pages/story.html', info=story, loggedin=isLoggedIn())
    return abort(404)


@bp.route('/read/<url>/comments', methods=['GET', 'POST'])
def comments(url):
    form = forms.CommentForm(request.form)
    if request.method == 'GET':
        story = models.Story.by_url(url)
        comments = models.Comment.by_url(url)

        if not comments:
            return abort(404)

        return render_template('pages/comments.html', story=story, comments=comments, url=url, form=form, loggedin=isLoggedIn())

    if request.method == 'POST' and form.validate():
        comment = models.Comment(
            story=url,
            author=g.user.username,
            parent_comment=None,
            comment=form.comment.data
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('story_comments', url=url))


@bp.route('/read/<url>/reviews', methods=['GET', 'POST'])
def reviews(url):
    form = forms.ReviewForm(request.form)


@bp.route('/submit', methods=['GET', 'POST'])
def submit():
    if g.user == None:
        return redirect(url_for('account.login'))
    form = forms.SubmitForm(request.form)
    if request.method == 'POST' and form.validate():
        url = base64.urlsafe_b64encode(uuid.uuid1().bytes)[:5]
        story = models.Story(
            url=url,
            author=g.user.username,
            title=form.title.data.strip(),
            synopsis=form.synopsis.data.strip(),
            story=form.story.data
        )
        db.session.add(story)
        db.session.commit()
        return redirect(url_for('story.read', url=url))
    return render_template('pages/submit.html', form=form, loggedin=isLoggedIn())

website/templates/_formhelpers.html
{% macro render_field(field) %}

<div class="form-group {% if field.errors %}has-danger{% endif %}"> 
{% if field.label.text != '' %}<label class="form-control-label" for="{{ field.id }}">{{ field.label.text }}</label> {% endif %} 
{{ field(**kwargs)|safe }} 
{% if field.errors %}
	<div class="form-control-feedback">
		{% for error in field.errors %}
		{{ error }}
		{% endfor %}
	</div>
	{% endif %} 
	{% if field.description %}<small class="form-text text-muted">{{ field.description }}</small> {% endif %}
</div>
{% endmacro %}

{% macro preview_markdown(id, preview_id) %}
<script src="//cdnjs.cloudflare.com/ajax/libs/commonmark/0.27.0/commonmark.min.js"></script>
<script type="text/javascript">
	$(document).ready(function () {
		var reader = new commonmark.Parser({ safe: true });
		var writer = new commonmark.HtmlRenderer({ safe: true });

		var parsed = reader.parse($("#{{ id }}").val());
		var result = writer.render(parsed);

		$("#{{ id }}").keydown(function (evt) {
				toParse = $("#{{ id }}").val();
				parsed = reader.parse(toParse);
				result = writer.render(parsed);
				$("#{{ preview_id }}").html(result);
		});
	});
</script>
{% endmacro %}

website/templates/base_template.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Base Template</title>

	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap//4.0.0-beta.2/css/bootstrap.min.css">

	<!-- Custom styles for this template -->
	<link href="../static/css/main.css" rel="stylesheet">
	<link href="../static/css/bootstrap.css" rel="stylesheet">
</head>

<body>
	<!--
	<nav class="navbar navbar-light navbar-toggleable-md">
		<div class="container">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav"
			    aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
			<a class="navbar-brand" href="#">Website!</a>

			<div class="collapse navbar-collapse" id="nav">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="#">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Story list</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Submit a story</a>
					</li>
				</ul>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="#"><strong>Log in</strong></a>
					</li>
					<li class="nav-item">
						<a class="btn btn-primary" href="#">Sign up</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
-->
<nav class="navbar navbar-light navbar-expand-md">
	<a class="navbar-brand" href="#">
		Website!</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav"
		 aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="nav">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="#">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Story list</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Submit a story</a>
				</li>
			</ul>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="#">
						<strong>Log in</strong>
					</a>
				</li>
				<li class="nav-item">
					<a class="btn btn-primary" href="#">Sign up</a>
				</li>
			</ul>
		</div>
</nav>

	<div class="container">
		<div class="jumbotron">
			<h1>Navbar example</h1>
			<p class="lead">This example is a quick exercise to illustrate how fixed to top navbar works. As you scroll, it will remain fixed to the
				top of your browser's viewport.</p>
			<a class="btn btn-lg btn-primary" href="../../components/navbar/" role="button">View navbar docs &raquo;</a>
		</div>
	</div>


	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
	    crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</body>

</html>

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}</title>

	<meta property="og:site_name" content="{{ config.SITE_NAME }}">
	<meta property="og:title" content="{{ self.title() }}"> 
	{% block metadata %} {# Filled by children #} {% endblock %}
	
	<!-- Latest compiled and minified CSS -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">
	
	<!-- Custom styles for this template -->
	<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/theme.css') }}" rel="stylesheet">
</head>

<body>
	{% block navbar %} {% endblock %} 
	{% block content%} {# This is the main stuff #} {% endblock %}
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

	{% block customjs %} {% endblock %}
</body>
</html>

website/templates/navbar.html
<header class="navbar navbar-expand-md navbar-inverse bg-primary">
	<nav class="container">
		<div class="d-flex justify-content-between">
			<a class="navbar-brand" href="{{url_for('main.home') }}">Website!</a>
			<button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav" aria-expanded="false"
			 aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
		<div class="collapse navbar-collapse" id="nav">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item{% if request.path == url_for('main.home') %} active{% endif %}">
					<a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
				</li>
				<li class="nav-item{% if request.path == url_for('story.list') %} active{% endif %}">
					<a class="nav-link" href="{{ url_for('story.list') }}">Story list</a>
				</li>
				<li class="nav-item{% if request.path == url_for('story.submit') %} active{% endif %}">
					<a class="nav-link" href="{{ url_for('story.submit') }}">Submit a story</a>
				</li>
				{% if g.user and g.user.rank > 1 %}
				<li class="nav-item{% if request.path == url_for('admin.home') %} active{% endif %}">
					<a class="nav-link" href="{{ url_for('admin.home') }}">Admin Area</a>
				</li>
				{% endif %}

			</ul>
			{% if not g.user %}

			<ul class="navbar-nav">
				<li class="nav-item{% if request.path == url_for('account.login') %} active{% endif %}">
					<a class="nav-link" href="{{ url_for('account.login') }}">
						<strong>Log in</strong>
					</a>
				</li>
				<li class="nav-item{% if request.path == url_for('account.signup') %} active{% endif %}">
					<a class="btn btn-primary align-middle" href="{{ url_for('account.signup') }}">Sign up</a>
				</li>
			</ul>
			{% else %}
			<ul class="navbar-nav ml-auto">
				<li class="nav-item{% if request.path == url_for('account.logout') %} active{% endif %}">
					<a class="nav-link" href="{{ url_for('account.logout') }}">
						<strong>Log out</strong>
					</a>
				</li>
				<li class="nav-item{% if request.path == url_for('account.home') %} active{% endif %}">
					<a class="btn btn-outline-secondary" href="{{ url_for('account.home') }}">
						<i class="fa fa-user-circle" aria-hidden="true"></i> Your Account</a>
				</li>
			</ul>
			{% endif %}
		</div>
	</nav>
</header>