website/views/account.py
from flask import g, request, url_for, redirect, session, render_template, make_response, current_app, Blueprint, abort, jsonify

from website import models, forms
from website.extensions import db
import uuid
import sys
from datetime import datetime
from ipaddress import ip_address

app = current_app
bp = Blueprint('account', __name__, url_prefix='/account')


@bp.route('/')
def home():
    if not isLoggedIn():
        return redirect(url_for('account.login'))

    userinfo = models.User.by_username(g.user.username)
    storyLen = models.Story.count_by_username(g.user.username)
    return render_template('pages/account.html', user=userinfo, storylen=storyLen)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if g.user:
        return redirect(redirect_url())

    form = forms.LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data.strip()
        password = form.password.data

        user = models.User.by_username(username)
        if (not user or password.join(user.salt) != (user.password)):
            return redirect(url_for('account.login', error='valfail'))

        user.last_login_date = datetime.utcnow()
        user.last_login_ip = ip_address(request.remote_addr).packed

        db.session.add(user)
        db.session.commit()

        g.user = user
        session['user_id'] = user.id
        session.permanent = True
        session.modified = True
        return redirect(redirect_url())

    return render_template('pages/login.html', form=form, error=request.args.get('error'))


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if g.user:
        return redirect(url_for(redirect_url()))

    form = forms.SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = models.generateSalt()
        user = models.User(username=form.username.data.strip(),
                           password=form.password.data,
                           salt=salt,
                           last_ip = ip_address(request.remote_addr).packed)
        db.session.add(user)
        db.session.commit()

        g.user = user
        session['user_id'] = user.id
        session.permanent = True
        session.modified = True
        return redirect(url_for('main.home'))

    return render_template('pages/signup.html', form=form)


@bp.route('/logout')
def logout():
    g.user = None
    session.permanent = False
    session.modified = False
    
    response = make_response(redirect(url_for('main.home')))
    response.set_cookie(app.session_cookie_name, expires=0)
    return response


@bp.route('/delete')
@bp.route('/delete/<username>')
@bp.route('/delete/<username>/<token>', methods=['POST'])
def delete(username = None, token = None):
    if g.user == None or username != g.user.username:
        abort(404)
        return
    # Update this to its own table in db
    if token is None:
        tempTok = uuid.uuid4().hex
        session['delete_token'] = tempTok
        return jsonify(tempTok)

    if token is not None and 'delete_token' not in session:
        abort(403)
        return

    if token is not None and 'delete_token' in session and g.user.username == username:
        if token != session['delete_token']:
            abort(403)
            return
        
        user = models.User.by_username(g.user.username)
        models.Story.delete_by_username(g.user.username)
        db.session.delete(user)
        db.session.commit()

        return redirect(url_for('account.logout'))

    return redirect(redirect_url())



@bp.route('/settings')
def settings():
    userinfo = models.User.by_username(g.user.username)
    storyLen = models.Story.count_by_username(g.user.username)
    last_ip += "{0}".format(ip_address(userinfo.last_login_ip))

    return render_template('pages/account.html', user=userinfo, storylen=storyLen, last_ip = ip)


@bp.route('/stories')
def stories():
    userinfo = models.User.by_username(g.user.username)
    stories = models.Story.list_by_username(g.user.username)
    storyLen = models.Story.count_by_username(g.user.username)

    return render_template('pages/account.html', user=userinfo, stories=stories, storylen=storyLen)



def redirect_url():
    home_url = url_for('main.home')

    url = request.args.get('next') or \
        request.referrer or \
        home_url
    if url == request.url:
        return home_url

    return url


def isLoggedIn():
    return g.user is not None

website/views/story.py
from flask import g, request, url_for, redirect, session, render_template, make_response, current_app, Blueprint, abort

from website import models, forms
from website.extensions import db
from website.views.main import isMobile
from website.views.account import isLoggedIn, redirect_url

import base64
import uuid

app = current_app
bp = Blueprint('story', __name__, url_prefix='/story')


@bp.route('/list', defaults={'extra': None})
@bp.route('/list/<extra>')
def list(extra=None):
    if not isMobile():
        stories = models.Story.get_list()
        if extra is not None:
            extra = extra.lower()
            if extra != 'top' and extra != 'latest' and extra != 'alphabetical':
                return abort(404)
        return render_template('pages/list.html', sort=extra, result=stories, loggedin=isLoggedIn())


@bp.route('/read/<url>')
def read(url):
    story = models.Story.by_url(url)

    if story:
        return render_template('pages/story.html', info=story, loggedin=isLoggedIn())
    return abort(404)


@bp.route('/read/<url>/comments', methods=['GET', 'POST'])
def comments(url):
    form = forms.CommentForm(request.form)
    if request.method == 'GET':
        story = models.Story.by_url(url)
        comments = models.Comment.by_url(url)

        if not comments:
            return abort(404)

        return render_template('pages/comments.html', story=story, comments=comments, url=url, form=form, loggedin=isLoggedIn())

    if request.method == 'POST' and form.validate():
        comment = models.Comment(
            story=url,
            author=g.user.username,
            parent_comment=None,
            comment=form.comment.data
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('story_comments', url=url))


@bp.route('/read/<url>/reviews', methods=['GET', 'POST'])
def reviews(url):
    form = forms.ReviewForm(request.form)


@bp.route('/submit', methods=['GET', 'POST'])
def submit():
    if g.user == None:
        return redirect(url_for('account.login'))
    form = forms.SubmitForm(request.form)
    if request.method == 'POST' and form.validate():
        url = base64.urlsafe_b64encode(uuid.uuid1().bytes)[:5]
        story = models.Story(
            url=url,
            author=g.user.username,
            title=form.title.data.strip(),
            synopsis=form.synopsis.data.strip(),
            story=form.story.data
        )
        db.session.add(story)
        db.session.commit()
        return redirect(url_for('story.read', url=url))
    return render_template('pages/submit.html', form=form, loggedin=isLoggedIn())

website/views/user.py
from flask import g, request, url_for, redirect, session, render_template, make_response, current_app, Blueprint, abort

from website import models, forms
from website.extensions import db
from website.views.account import isLoggedIn

app = current_app
bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/')
def home():
    return redirect(url_for('main.home'))


@bp.route('/<username>')
def user(username):
    userinfo = models.User.by_username(username)

    if userinfo:
        stories = models.Story.list_by_username(username)
        storyLen = models.Story.count_by_username(username)
        return render_template('pages/user.html', user=userinfo, stories=stories, storylen=storyLen, loggedin=isLoggedIn())
    return abort(404)

website/templates/pages/account.html
{% extends 'layout.html' %}
{% block title %}{{ user.username }} - {{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %}

        {% if request.path == url_for('account.home') %}
        {% from 'pages/account_profile.html' import account_profile with context %}
        {% from 'pages/account_profile.html' import customjs as js with context %}
        {% endif %}
        
        {% if request.path == url_for('account.settings') %}
        {% from 'pages/account_settings.html' import account_settings with context %}
        {% from 'pages/account_settings.html' import customjs as js with context %}
        {% endif %}
        
        {% if request.path == url_for('account.stories') %}
        {% from 'pages/account_stories.html' import account_stories with context %}
        {% from 'pages/account_stories.html' import customjs as js with context %}
        {% endif %}

{% block content %}
<div class="container">
    <div class="col-12">
        <h1 class="username">USER: {{ user.username }}</h1>
        <hr>
        <section class="user-info text-muted">
            <ul class="list-inline">
                <li class="list-inline-item">Account type: <span class="badge badge-success">VIP</span></li>
                &nbsp;
                <li class="list-inline-item">Story count: {{ storylen }}</li>
            </ul>
        </section>

        <section class="user-pages">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link{% if request.path == url_for('account.home') %} active {% endif %}" href="{{ url_for('account.home') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if request.path == url_for('account.settings') %} active {% endif %}" href="{{ url_for('account.settings') }}">Settings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if request.path == url_for('account.stories') %} active {% endif %}" href="{{ url_for('account.stories') }}">Stories</a>
                </li>
            </ul>
        </section>
        
        
        {% if request.path == url_for('account.home') %}
        {{ account_profile() }}
        {% endif %}
        
        {% if request.path == url_for('account.settings') %}
        {{ account_settings() }}
        {% endif %}
        
        {% if request.path == url_for('account.stories') %}
        {{ account_stories() }}
        {% endif %}
    </div>
</div>

{% endblock %}

{% block customjs %}
        {{ js() }}
{% endblock %}

website/templates/pages/account_profile.html
{% macro account_profile() %}
<section class="user-content user-profile clearfix">
    <div class="user-info card">
        <div class="card-block">
            <dl>
                <dt>Last login date:</dt>
                <dd>{{user.last_login_date}}</dd>
                <dt>Last login IP:</dt>
                <dd>{{last_ip}}</dd>
            </dl>
        </div>
    </div>
</section>
{% endmacro %}

{% macro customjs() %}
{% endmacro %}

website/templates/pages/account_settings.html
{% macro account_settings() %}
<section class="user-content user-settings">

    <div class="delete-button">
        <button type="button" id="delete-button" class="btn btn-danger" data-target="#confirm-deletion" data-toggle="modal">Delete account.</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="confirm-deletion" tabindex="-1" role="dialog" aria-labelledby="confirm-deletion" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm deletion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    
                    <p>Are you sure you want to delete your account?</p>
                    <p class="text-danger"><strong>This action cannot be undone.</strong></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="confirm-delete-button" class="btn btn-danger">Confirm deletion</button>
                </div>
            </div>
        </div>
    </div>

</section>
{% endmacro %}

{% macro customjs() %}
<script>
       $(document).ready(function () {
            $("#confirm-delete-button").click(function () {
                $.get("{{url_for('account.delete')}}/{{user.username}}", function (getData) {
                    $.post("{{url_for('account.delete')}}/{{user.username}}/"+getData, function (postData) {
                        $("#confirm-deletion").modal().hide();
                        window.location.href = "{{ url_for('main.home')}}";
                    });
                });
            });
        });
    </script>
{% endmacro %}

website/templates/pages/account_stories.html
{% macro account_stories() %}
<section class="user-content user-stories">
    {% for story in stories %}
    <div class="card">
        <div class="card-block">
            <h4 class="card-title">{{ story.title }}</h4>
            <h6 class="card-subtitle mb-2 text-muted">Votes: {{ story.votes }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Date posted: {{ story.date_posted|timeformatted }}</h6>
            <p class="card-text">{{ story.synopsis }}</p>
            <a href="{{ url_for('story.read', url=story.url) }}" class="card-link btn btn-primary">Story</a>
        </div>
    </div>
    <br> {% endfor %}
</section>
{% endmacro %}

{% macro customjs() %}
{% endmacro %}

website/templates/pages/comments.html
{% extends 'layout.html' %} {% block title %}Comments :: {{ story.title }} - {{ config.SITE_NAME }}{% endblock %} {% block
navbar %}{% include 'navbar.html' %}{% endblock %} {% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="text-center">
                Comments for: {{ story.title }}
            </h1>
            <hr> {% if loggedin %} {% from '_formhelpers.html' import render_field %}
            <section class="create-comment">
                <form method="POST" action="{{ url_for('story.comments', url=url) }}">
                    {{ render_field(form.comment) }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </section>
            {% endif %}
            <section class="comments" id="comments">
                {% for comment in comments %}
                <div class="comment-thread" id="thread-{{comment.id}}">
                    <div class="comment">
                        <div class="card" id="comment-{{comment.id}}">
                            <div class="card-block">
                                <p class="card-title"><a href="{{ url_for('user.user', username=comment.author) }}" class="comment-link-commenter text-warning">{{ comment.author }}</a>                                    <span class=" text-muted small">posted: 12-12-1990</span></p>
                                <p class="card-text lead">{{ comment.comment }}</p>
                            </div>
                        </div>
                    </div>
                   
                </div>
                {% endfor %}
            </section>
        </div>
    </div>
</div>
{% endblock %} {% block customjs %}
<script>
</script>
{% endblock %}

website/templates/pages/index.html
{% extends 'layout.html' %}
{% block title %}{{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
<div class="container">
	<div class="col-12">
		<div class="jumbotron">
			<h1>
				Hi there!
			</h1>
			<p class="open-sans">Welcome to the simplistic story reader website focused on optimal reading ability.<br> Stories are rated based on votes
				that you make (you need to <a href="{{ url_for('account.signup') }}">create an account</a> to be able to do this).<br> Best of all, everything
				is free and you receive no ads unless you <a href="account/options">agree</a> to it.
			</p>
			<p><a class="btn btn-primary btn-lg" href="info/about">Learn more</a></p>
		</div>
	</div>
</div>
{% endblock %}

website/templates/pages/list.html
{% extends 'layout.html' %}
{% block title %}List - {{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
<div class="container">
	<div class="col-md-12">
		<h1 class="page-header text-center" id="top"><i class="fa fa-star"></i> Stories</h1>

		<table class="table table-bordered table-hover" id="table" cellspacing="0">
			<thead>
				<tr scope="row">
					<th style="width:20px;">#</th>
					<th>Title</th>
					<th>Synopsis</th>
					<th>Author</th>
					<th style="width:160px;">Date Posted</th>
					<th class="text-center" style="width:20px;">Votes</th>
					<th class="text-center" style="width:50px;">Link</th>
				</tr>
			</thead>
			<tbody>
				{% for info in result %}
				<tr>
					<th scope="row">{{ loop.index }}</th>
					<td> {{ info.title }} </td>
					<td> {{ info.synopsis }} </td>
					<td> {{ info.author }} </td>
					<td> {{ info.date_posted|timeformatted }} </td>
					<td class="text-center"> {{ info.votes }} </td>
					<td> <a class="btn btn-sm btn-primary" href="{{ url_for('story.read', url=info.url) }}">Click</a> </td>
				</tr> {% endfor %}

			</tbody>
		</table>
	</div>
</div>
{% endblock %}
{% block customjs %}
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>
<script>
	$(document).ready(function () {
		$('#table').DataTable({
			searching: false,
			"columnDefs": [{
				"orderable": false,
				"targets": [2, 6]
			}],
			{% if sort == 'top' %}
			"order": [
			[5, "desc"]
		] {% elif sort == 'latest' %}
		"order": [
			[4, "desc"]
		] {% elif sort == 'alphabetical' %}
		"order": [
			[1, "desc"]
		] {% endif %}
		});
	});
</script>
{% endblock %}

website/templates/pages/login.html
{% extends 'layout.html' %}
{% block title %}Log in - {{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
<div class="container">
	<div class="row justify-content-center">
		{% if error == 'valfail' %}
		<div class="alert alert-danger" role="alert">
			 <strong>Username or password is wrong</strong>
		</div>
		{% endif %}
		<div class="col-md-4">
			<div class="login">
				{% from '_formhelpers.html' import render_field %}
				<form method="POST" action="{{ url_for('account.login') }}">
					{{ render_field(form.username) }}
					{{ render_field(form.password) }}
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block customjs %}
{% endblock %}

website/templates/pages/signup.html
{% extends 'layout.html' %}
{% block title %}Sign up - {{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4">
			<div class="signup">
				{% from '_formhelpers.html' import render_field %}
				<form method="POST" action="{{ url_for('account.signup') }}">
					{{ render_field(form.username) }} 
					{{ render_field(form.password) }} 
					{{ render_field(form.password2) }}
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %} 
{% block customjs %}
{% endblock %}

website/templates/pages/story.html
{% extends 'layout.html' %} {% block title %}{{ info.title }} - {{config.SITE_NAME}}{% endblock %} {% block navbar %}{% include
'navbar.html' %}{% endblock %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
  <div class="col-8">
    <div class="page-header">
      <h1 class="text-center" id="container">
        {{ info.title }}
      </h1>
    </div>
    <button type="button" class="btn btn-info btn-lg btn-block" data-toggle="collapse" data-target="#info">
          Information and Synopsis
    </button>

    <div id="info" class="collapse collapse-in">
      <br>
      <div class="well well-xs">
        <dl class="row">
          <dt class="col-sm-2">Author: </dt>
          <dd class="col-sm-10">
            <a href="{{ url_for('user.user', username=info.author) }}">
              <u>{{ info.author }}</u>
            </a>
          </dd>
          <dt class="col-sm-2">Date posted: </dt>
          <dd class="col-sm-10">{{ info.date_posted|timeformatted }}</dd>
          <dt class="col-sm-2">Votes: </dt>
          <dd class="col-sm-10">{{ info.votes }}</dd>
          <dt class="col-sm-2">Synopsis: </dt>
          <dd class="col-sm-10">{{ info.synopsis }}</dd>
        </dl>
        <a href="{{ url_for('story.comments', url=info.url) }}" class="btn btn-block btn-primary text-center">View comments.</a>
      </div>
    </div>
    <br>
    <hr>
    <div id="story" style="visibility:hidden;">{{ info.story }}</div>
  </div>
  </div>
</div>
{% endblock %}
{% block customjs %}
<script src="//cdnjs.cloudflare.com/ajax/libs/commonmark/0.27.0/commonmark.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
    var reader = new commonmark.Parser({ safe: true });
    var writer = new commonmark.HtmlRenderer({ safe: true });
    var parsed = reader.parse($("#story").text());

    writer.softbreak = "<br>";
    var result = writer.render(parsed);
    $("#story").html(result);
    $("#story").removeAttr("style");
  });
</script>
{% endblock %}

website/templates/pages/submit.html
{% extends 'layout.html' %}
{% block title %}Submit a Story - {{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
<div class="container">
	<div class="row">
				{% if loggedin %} 
				{% from '_formhelpers.html' import render_field %}
				<div class="col">
					<div class="submit">
						
					<form method="POST" action="{{ url_for('story.submit') }}">
						
						{{ render_field(form.story) }}
						<p class="text-muted"><small>We use <a href="http://commonmark.org/help/">markdown</a> to write our stories!</small></p>
						{{ render_field(form.title) }}
						{{ render_field(form.synopsis) }}
						<button type="submit" class="btn btn-primary">Submit</button>
					</form>
					
					</div>
				</div>
				<div class="col">
					<div class="hidden-sm-down">
						<br>
					</div>
					<div id="story-preview">
						
					</div>
				</div>
				{% else %}
				<div class="jumbotron">
					<h1>
						You are not logged in.
					</h1>
					<div>
						Hi there! It seems that you are not logged in. Unfortunately you can only submit stories if you are logged in.
						</div>
						<br>
					<div>
						<a class="btn btn-primary btn-lg" href="{{ url_for('account.login') }}">Log in</a> or <a class="btn btn-secondary btn-lg" href="{{ url_for('account.signup') }}">Sign up</a>
						</div>
				</div>
				{% endif %}
	</div>
</div>
{% endblock %}
{% block customjs %}
{% from '_formhelpers.html' import preview_markdown %}
{{ preview_markdown('story-text', 'story-preview') }} 
{% endblock %}

website/templates/pages/user.html
{% extends 'layout.html' %}
{% block title %}{{ user.username }} - {{config.SITE_NAME}}{% endblock %} 
{% block navbar %}{% include 'navbar.html' %}{% endblock %} 
{% block content %}
<div class="container">
    <div class="col-12">
        <h1 class="username">USER: {{ user.username }}</h1>
        <hr>
        <section class="user-info text-muted">
            <ul class="list-inline">
                <li class="list-inline-item">Account type: <span class="badge badge-success">VIP</span></li>
                &nbsp;
                <li class="list-inline-item">Story count: {{ storylen }}</li>
            </ul>
        </section>

        {% if accountSettings %}
        <section class="user-pages">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('account.home') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('account.settings') }}">Settings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('account.stories') }}">Stories</a>
                </li>
            </ul>
        </section>
        <br>
        {% endif %}
        
        <section class="user-stories">
             {% for story in stories %}
            <div class="card">
                <div class="card-block">
                    <h4 class="card-title">{{ story.title }}</h4>
                    <h6 class="card-subtitle mb-2 text-muted">Votes: {{ story.votes }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Date posted: {{ story.date_posted|timeformatted }}</h6>
                    <p class="card-text">{{ story.synopsis }}</p>
                    <a href="{{ url_for('story.read', url=story.url) }}" class="card-link btn btn-primary">Story</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </section>
    </div>
</div>

{% endblock %}